# To run books servics:
# image: shaikkhajaibrahim/libbookssvc:1.0
# environmental variables:
# DATABASE_URL: “postgresql://<POSTGRES_USER>:<POSTGRES_PASSWORD>@<name or ip of the container>:5432/<POSTGRSS_DB>“
# SECRET_KEY: ‘YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k’
# port: 8000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service-rs
  annotations:
    kubernetes.io/change-cause: "updated image v1.0"
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge:
        maxUnavailable:
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books-service-container
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          # env:
          #   - name: SECRET_KEY
          #     value: 'YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k'
          #   - name: DATABASE_URL
          #     value: "postgresql://user:password@books-db:5432/booksdb"
          envFrom:
            - configMapRef:
                name: books-service-rs-config
          ports:
            - containerPort: 8000

---

## Create Service Type ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: books-svc-svc
spec:
  type: ClusterIP
  selector:
    app: books-service
  ports:
  - port: 8000
    targetPort: 8000