---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-db-rs-config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-db-rs-config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booksdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-rs-config
data:
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
  DATABASE_URL: "postgresql://user:password@users-db:5432/usersdb
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-service-rs-config
data:
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
  DATABASE_URL: "postgresql://user:password@books-db:5432/booksdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webstore-config
data:
  REACT_APP_BACKEND_API_URL: "http://users-svc-svc:8000/api/v1"
  REACT_APP_BOOKS_API_URL: "http://books-svc-svc:8000/api/v1/books"
  REACT_APP_USERS_API_URL: "http://users-svc-svc:8000/api/v1/users"
  
