
apiVersion: apps/v1
kind: ReplicaSet
metadate:
  name: users-db-rs
  labels: users-DB
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      Database: users-DB
  template:
    metadata:
      name: users-db-pod
      labels: 
       Database: users-DB
    spec:
      containers:
        - name: users-db-container
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          ports:
            - containerPort: 5432
---

# Create Service 

apiVersion: v1
kind: Service
metadata:
  name: users-db-svc
spec:
  type: ClusterIP
  selector:
    Database: users-DB
  ports:
    - port: 5432
      targetPort: 5432
    


  



