# To run library webstore
   # image: shaikkhajaibrahim/libwebstore:1.0
# environmental variables
   # REACT_APP_BACKEND_API_URL: http://<UserServiceName>:8000/api/v1
   # REACT_APP_BOOKS_API_URL: http://<UserServiceName>:8000/api/v1/books
   # REACT_APP_USERS_API_URL: http://<booksServiceName>:8000/api/v1/users
   #port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-webstore-rs
  labels:
    app: webstore
  annotations:
    kubernetes.io/change-cause: "updated image v1.0"
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: webstore
  strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge:
        maxUnavailable:
  template:
    metadata:
      labels:
        app: webstore
    spec:
      containers:
        - name: webstore
          image: shaikkhajaibrahim/libwebstore:1.0
          resources:
            requests:
              memory: 64M
              cpu: 200m
            limits:
              memory: 128M
              cpu: 500m
          ports:
            - containerPort: 3000
          # env:
          #   - name: REACT_APP_BACKEND_API_URL
          #     value: http://users-svc-svc:8000/api/v1
          #   - name: REACT_APP_BOOKS_API_URL
          #     value: http://books-svc-svc:8000/api/v1/books
          #   - name: REACT_APP_USERS_API_URL
          #     value: http://users-svc-svc:8000/api/v1/users
          envFrom:
            -  configMapRef:
                 name: webstore-config

---
apiVersion: v1
kind: Service
metadata:
  name: librarystore-svc
spec:
  type: LoadBalancer
  selector:
    app: webstore
  ports:
  - port: 80
    targetPort: 3000





