apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db-sts
  labels:
    app: users-db
spec:
  minReadySeconds: 5
  replicas: 2
  serviceName: users-db-svc
  selector:
    matchLabels:
      db: users
  template:
    metadata:
      labels:
        db: users
    spec:
      automountServiceAccountToken: "false"
      containers:
        - image: postgres:15-alpine
          name: usersdb
          # env:
          #   - name: POSTGRES_USER
          #     value: user
          #   - name: POSTGRES_PASSWORD
          #     value: password
          #   - name: POSTGRES_DB
          #     value: usersdb
          envFrom:
            # - configMapRef:
            #     name: users-db-rs-config
            - secretRef:
                name: users-db-rs-secrets
            
          resources:
            requests:
              memory: 64M
              cpu: 200m
            limits:
              memory: 128M
              cpu: 500m
          ports:
            - containerPort: 5432
          volumeMounts: 
            - name: users-pvc
              mountPath: /var/lib/postgresql/data
              subPath: data
---
apiVersion: v1
kind: Service
metadata:
  name: users-db-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: users
  ports:
    - port: 5432
      targetPort: 5432
      

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    resources:
      storage: 1Gi
