apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
spec:
  containers:
    - name: mysql-con
      image: mysql:9
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: sql-pod-config
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldb
  volumes:
    - name: mysqldb
      persistentVolumeClaim:
        claimName: mysql-pvc