---
apiVersion: v1
kind: Namespace
metadata:
  namespace: qa
  labels:
    env: qa
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx 