---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  annotations:
        kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      name: Pod-tag
      labels:
        app: web
    spec:
      containers:
        - name: container
          image: shaikkhajaibrahim/dmtest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64M
              cpu: 200m
            limits:
              memory: 128M
              cpu:500m

---
apiVersion: v1
kind: Service
metadata:
  name: deploy-svc
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80

      
