apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    env: dev
spec:
  containers:
    - name: myapp
      image: shaikkhajaibrahim/spcjan2024:1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 250m
          memory: 64M
        limits:
          cpu: 500m
          memory: 256M
      
          