apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    env: app
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      env: app
  template:
    metadata:
      name: pod
      labels:
        env: app
        version: v1.0
    spec:
      containers:
        - name: spc-rs-container
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
      nodeSelector:
        type: aks-nodepool1-32331479-vmss000001