apiVersion: v1
kind: Pod
metadata:
  name: activity2
  Namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: {{ .Release.Name }}-container
      image: {{ .Values.image }}
    - name: linux
      image: alpine
      args: {{ .Values.args | toYaml | nindent 8}}
        